### ISSUE TITLE
Cell-Corner

### ISSUE THREAD

**Issue by bpichon** [excellenteasy/bradypodion#29]
When group a table everything seems right. 
But... if i change the last-cells display css-value to 'hidden', it just hides the last cell. It does not adjust the corners.

![corners](https://f.cloud.github.com/assets/4584375/1013493/28830af6-0b8b-11e3-89ee-d3a2f58b8a7b.JPG)

There would be a quite easy way to fix this bug, in js. (case-specific -> i mean outside the framework)
Maybe you already want to fix it directly in your framework.

**Comment by davidpfahler** [comment]
That happens because the styling (rounded corners) is applied to the last cell. The questions is, why do you set the last cell to `visibility: hidden`? What are you trying to achieve? This should most probably be done with angular, not by modifying CSS. 

For example, if you want to hide a cell conditionally, put the condition on the scope, then use the ngIf directive:

``` javascript
// somewhere in your controller
$scope.hideLastCell = true;
```

In your html:

``` html
<bp-cell>cell 1</bp-cell>
<bp-cell ng-if="!hideLastCell">cell 2</bp-cell>
```

This way, you can dynamically change the behavior at runtime.
